name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocaml-compiler: ["4.13.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: opam install uutf alcotest
      - run: opam exec -- dune build
      - name: Run tests
        run: opam exec -- dune runtest
